import { useState } from 'react';

interface SOPTemplate {
  id: string;
  name: string;
  category: string;
  icon: string;
  description: string;
}

interface GeneratedSOP {
  id: string;
  title: string;
  category: string;
  content: string;
  createdAt: string;
  sections: string[];
}

const SOPBuilder = () => {
  const [selectedTemplate, setSelectedTemplate] = useState<SOPTemplate | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [sopTitle, setSopTitle] = useState('');
  const [sopDescription, setSopDescription] = useState('');
  const [generatedSOPs, setGeneratedSOPs] = useState<GeneratedSOP[]>([]);
  const [selectedSOP, setSelectedSOP] = useState<GeneratedSOP | null>(null);

  const templates: SOPTemplate[] = [
    {
      id: '1',
      name: 'Admission Process',
      category: 'Academic',
      icon: 'fa-user-plus',
      description: 'Student admission and enrollment procedures'
    },
    {
      id: '2',
      name: 'Exam Conduct',
      category: 'Academic',
      icon: 'fa-clipboard-list',
      description: 'Standard exam administration protocol'
    },
    {
      id: '3',
      name: 'Safety & Emergency',
      category: 'Safety',
      icon: 'fa-shield-alt',
      description: 'Emergency response and safety protocols'
    },
    {
      id: '4',
      name: 'Library Management',
      category: 'Operations',
      icon: 'fa-book',
      description: 'Library operations and book management'
    },
    {
      id: '5',
      name: 'Event Organization',
      category: 'Events',
      icon: 'fa-calendar-alt',
      description: 'College/University events planning and execution'
    },
    {
      id: '6',
      name: 'Transport Management',
      category: 'Operations',
      icon: 'fa-bus',
      description: 'University/College transport operations and safety'
    },
    {
      id: '7',
      name: 'Fee Collection',
      category: 'Finance',
      icon: 'fa-money-bill-wave',
      description: 'Fee payment and collection procedures'
    },
    {
      id: '8',
      name: 'Staff Onboarding',
      category: 'HR',
      icon: 'fa-user-tie',
      description: 'New staff recruitment and onboarding'
    }
  ];

  const generateSOP = () => {
    if (!selectedTemplate || !sopTitle) return;

    setIsGenerating(true);

    setTimeout(() => {
      const newSOP: GeneratedSOP = {
        id: Date.now().toString(),
        title: sopTitle,
        category: selectedTemplate.category,
        content: generateSOPContent(selectedTemplate, sopTitle, sopDescription),
        createdAt: new Date().toLocaleDateString(),
        sections: ['Purpose', 'Scope', 'Procedure', 'Responsibilities', 'Documentation']
      };

      setGeneratedSOPs([newSOP, ...generatedSOPs]);
      setSelectedSOP(newSOP);
      setIsGenerating(false);
      setSopTitle('');
      setSopDescription('');
      setSelectedTemplate(null);
    }, 2000);
  };

  const generateSOPContent = (template: SOPTemplate, title: string, description: string) => {
    return `# ${title}

## Purpose
This Standard Operating Procedure (SOP) defines the process for ${template.name.toLowerCase()} at our institution.

${description ? `## Overview\n${description}\n\n` : ''}
## Scope
This procedure applies to all staff members involved in ${template.name.toLowerCase()} activities.

## Procedure

### Step 1: Initial Setup
- Review all necessary documentation
- Ensure all required resources are available
- Verify compliance with institutional policies

### Step 2: Execution
- Follow the established workflow
- Maintain accurate records throughout the process
- Communicate with relevant stakeholders

### Step 3: Quality Check
- Review completed work for accuracy
- Ensure all requirements have been met
- Document any deviations or issues

### Step 4: Completion
- Finalize all documentation
- Archive records as per retention policy
- Update tracking systems

## Responsibilities

### Administrator
- Overall supervision and approval
- Resource allocation
- Policy compliance verification

### Staff Members
- Execute procedures as outlined
- Maintain documentation
- Report issues or concerns

### Quality Assurance
- Regular audits and reviews
- Process improvement recommendations
- Training and support

## Documentation
All related documentation must be maintained for a minimum of 5 years and include:
- Process checklists
- Approval records
- Communication logs
- Incident reports (if any)

## Review and Updates
This SOP should be reviewed annually or when significant changes occur in the process.

---
*Generated by EdgeUp AI SOP Builder on ${new Date().toLocaleDateString()}*`;
  };

  const exportSOP = (sop: GeneratedSOP, format: string) => {
    alert(`Exporting "${sop.title}" as ${format}... (Feature will be implemented)`);
  };

  return (
    <div className="sop-builder-page">
      {/* Page Header */}
      <div className="smgmt-header">
        <div className="header-left">
          <h1><i className="fas fa-file-signature"></i> SOP Builder & Documentation</h1>
          <p>AI-powered standard operating procedures and documentation management</p>
        </div>
        <div className="header-actions">
          <button className="btn-primary" onClick={() => alert('Create SOP functionality')}>
            <i className="fas fa-plus"></i>
            Create SOP
          </button>
          <button className="btn-secondary" onClick={() => alert('View All SOPs functionality')}>
            <i className="fas fa-folder-open"></i>
            View All SOPs
          </button>
        </div>
      </div>

      {/* Template Selection */}
      <div className="sop-templates-card">
        <div className="sop-header">
          <div className="sop-header-icon">
            <i className="fas fa-file-alt"></i>
          </div>
          <div>
            <h2>SOP Templates</h2>
            <p>Select a template to create standardized procedures</p>
          </div>
        </div>

        <div className="templates-grid">
          {templates.map((template) => (
            <div
              key={template.id}
              className={`template-card ${selectedTemplate?.id === template.id ? 'selected' : ''}`}
              onClick={() => setSelectedTemplate(template)}
            >
              <div className="template-icon">
                <i className={`fas ${template.icon}`}></i>
              </div>
              <h3>{template.name}</h3>
              <span className="template-category">{template.category}</span>
              <p>{template.description}</p>
            </div>
          ))}
        </div>
      </div>

      {/* SOP Creation Form */}
      {selectedTemplate && (
        <div className="sop-creation-card">
          <div className="sop-header">
            <div className="sop-header-icon">
              <i className="fas fa-magic"></i>
            </div>
            <div>
              <h2>Generate SOP with AI</h2>
              <p>Template: {selectedTemplate.name}</p>
            </div>
          </div>

          <div className="sop-form">
            <div className="form-group">
              <label>
                <i className="fas fa-heading"></i>
                SOP Title *
              </label>
              <input
                type="text"
                placeholder="e.g., College Admission Process 2024"
                value={sopTitle}
                onChange={(e) => setSopTitle(e.target.value)}
              />
            </div>

            <div className="form-group">
              <label>
                <i className="fas fa-align-left"></i>
                Additional Details (Optional)
              </label>
              <textarea
                placeholder="Provide any specific requirements or context for the AI to generate better content..."
                value={sopDescription}
                onChange={(e) => setSopDescription(e.target.value)}
                rows={4}
              />
            </div>

            <div className="ai-suggestions">
              <div className="suggestion-header">
                <i className="fas fa-lightbulb"></i>
                <span>AI Suggestions</span>
              </div>
              <div className="suggestions-list">
                <div className="suggestion-item" onClick={() => setSopDescription('Include COVID-19 safety protocols and online admission options')}>
                  Include COVID-19 safety protocols
                </div>
                <div className="suggestion-item" onClick={() => setSopDescription('Add faculty-student communication guidelines')}>
                  Add faculty-student communication
                </div>
                <div className="suggestion-item" onClick={() => setSopDescription('Include special needs accommodation procedures')}>
                  Include special needs procedures
                </div>
              </div>
            </div>

            <div className="form-actions">
              <button
                className="cancel-btn"
                onClick={() => {
                  setSelectedTemplate(null);
                  setSopTitle('');
                  setSopDescription('');
                }}
              >
                Cancel
              </button>
              <button
                className="generate-sop-btn"
                onClick={generateSOP}
                disabled={isGenerating || !sopTitle}
              >
                {isGenerating ? (
                  <>
                    <i className="fas fa-spinner fa-spin"></i>
                    Generating SOP...
                  </>
                ) : (
                  <>
                    <i className="fas fa-robot"></i>
                    Generate SOP with AI
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Generated SOPs List */}
      {generatedSOPs.length > 0 && (
        <div className="sop-documents-section">
          <div className="section-split">
            {/* SOPs List */}
            <div className="sop-list-card">
              <div className="sop-list-header">
                <h3><i className="fas fa-folder-open"></i> Generated SOPs ({generatedSOPs.length})</h3>
              </div>
              <div className="sop-list">
                {generatedSOPs.map((sop) => (
                  <div
                    key={sop.id}
                    className={`sop-item ${selectedSOP?.id === sop.id ? 'active' : ''}`}
                    onClick={() => setSelectedSOP(sop)}
                  >
                    <div className="sop-item-icon">
                      <i className="fas fa-file-alt"></i>
                    </div>
                    <div className="sop-item-info">
                      <h4>{sop.title}</h4>
                      <div className="sop-item-meta">
                        <span className="sop-category">{sop.category}</span>
                        <span className="sop-date">{sop.createdAt}</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* SOP Preview */}
            {selectedSOP && (
              <div className="sop-preview-card">
                <div className="sop-preview-header">
                  <div>
                    <h3>{selectedSOP.title}</h3>
                    <span className="preview-category">{selectedSOP.category}</span>
                  </div>
                  <div className="preview-actions">
                    <button onClick={() => exportSOP(selectedSOP, 'PDF')} className="export-icon-btn">
                      <i className="fas fa-file-pdf"></i>
                    </button>
                    <button onClick={() => exportSOP(selectedSOP, 'Word')} className="export-icon-btn">
                      <i className="fas fa-file-word"></i>
                    </button>
                    <button onClick={() => exportSOP(selectedSOP, 'Print')} className="export-icon-btn">
                      <i className="fas fa-print"></i>
                    </button>
                  </div>
                </div>
                <div className="sop-preview-content">
                  <pre>{selectedSOP.content}</pre>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Empty State */}
      {generatedSOPs.length === 0 && !selectedTemplate && (
        <div className="sop-empty-state">
          <div className="empty-state-icon">
            <i className="fas fa-file-alt"></i>
          </div>
          <h3>No SOPs Created Yet</h3>
          <p>Select a template above to generate your first Standard Operating Procedure</p>
        </div>
      )}
    </div>
  );
};

export default SOPBuilder;
